# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

# Defines what agent the job will run on
pool:
  vmImage: 'ubuntu-latest'

# a job has steps
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'




# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Azure subscription 1(4ee77189-d18b-4ba6-8d49-dac5b0422010)'
#     appType: 'webApp'
#     WebAppName: 'Project1-William-Nesham'
#     packageForLinux: '$(System.DefaultWorkingDirectory)/publish'



- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'WilliamsSonar'
    organization: '2006-jun15-net'
    scannerMode: 'MSBuild'
    projectKey: '2006-jun15-net_william-project-1'
    projectName: 'William Project 1 Stores'
    extraProperties: 'sonar.exclusions=**/lib/**, **/wwwroot/**'

- script: dotnet build ./ProjectOne
  displayName: 'dotnet build'

- task: SonarCloudAnalyze@1
  displayName: sonarcloud run analysis

- task: SonarCloudPublish@1
  displayName: sonarcloud publish
  inputs:
    pollingTimeoutSec: '300'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo This is a multi-line script thanks to the pipe.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'