# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

pr:
- master

# Defines what agent the job will run on
pool:
  vmImage: 'ubuntu-latest'

# a job has steps
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: dotnet build
  displayName: 'dotnet build ./ProjectOne'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo This is a multi-line script thanks to the pipe.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'